export enum CommunityCategories {
    MUSIC = 'music',
    DANCE = 'dance',
    ART = 'art',
    FASHION = 'fashion',
    FOOD = 'food',
    TRAVEL = 'travel',
    SPORTS = 'sports',
    TECHNOLOGY = 'technology',
    EDUCATION = 'education',
    HEALTH = 'health',
    LIFESTYLE = 'lifestyle',
    INFLUENCER = 'influencer',
    ENTERTAINMENT = 'entertainment',
    GAMING = 'gaming',
    NATURE = 'nature',
    PHOTOGRAPHY = 'photography',
    FILM = 'film',
    LITERATURE = 'literature',
    BUSINESS = 'business',
    SHOPPING = 'shopping',
}