import { Column, Entity, JoinTable, ManyToMany, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { HitTweet } from "../../hit-tweets/entities/hit-tweet.entity.js";
import { Media } from "../../media/entities/media.entity.js";
import { Outfit } from "../../outfits/entities/outfit.entity.js";
import { Highlight } from "../../highlights/entities/highlight.entity.js";
import { SurpriseSong } from "../../surprise-song/entities/surprise-song.entity.js";
import { Location } from "../../location/entities/location.entity.js";

/**
 * Represents an event entity in the application.
 */
@Entity()
export class Event {

    /**
     * The unique identifier for the event.
     */
    @PrimaryGeneratedColumn()
    eventId: number;

    /**
     * The date of the event.
     */
    @Column({ type: 'date'})
    date: Date;

    /**
     * The setlist for the event, stored as a simple array of strings. This field is optional and can be null.
     */
    @Column('simple-array', { nullable: true })
    setlist: string[];

    /**
     * The number of tickets sold for the event. This field is optional and can be null.
     */
    @Column({ type: 'integer',nullable: true })
    ticketsSold: number;

    /**
     * The revenue generated by the event. This field is optional and can be null.
     */
    @Column({ type: 'decimal', nullable: true })
    revenue: number;

    /**
     * The attendance for the event. This field is optional and can be null.
     */
    @Column({ type: 'integer', nullable: true })
    attendance: number;

    /**
     * The media associated with the event.
     */
    @OneToMany(() => Media, (media) => media.event, { cascade: true })
    media: Media[];

    /**
     * The outfits associated with the event.
     */
    @ManyToMany(() => Outfit, (outfit) => outfit.events)
    outfits: Outfit[];

    /**
     * The highlights associated with the event.
     */
    @OneToMany(() => Highlight, (highlight) => highlight.event, { cascade: true })
    highlights: Highlight[];

    /**
     * The hit tweets associated with the event.
     */
    @OneToMany(() => HitTweet, (tweet) => tweet.event, { cascade: true })
    tweets: HitTweet[];

    /**
     * The surprise songs associated with the event.
     */
    @ManyToMany(() => SurpriseSong, (surpriseSong) => surpriseSong.events)
    @JoinTable()
    surpriseSongs: SurpriseSong[];

    /**
     * The location associated with the event.
     */
    @ManyToOne(() => Location, (location) => location.events)
    location: Location;
}
