import {
  IsArray,
  IsDateString,
  IsInt,
  IsNumber,
  IsOptional,
} from 'class-validator';

/**
 * DTO used to create an event.
 */
export class CreateEventDto {

  /**
   * The date of the event.
   */
  @IsDateString()
  date: string;

  /**
   * The setlist of the event.
   */
  @IsArray()
  @IsOptional()
  setlist?: string[];

  /**
   * The number of tickets sold for the event.
   */
  @IsInt()
  @IsOptional()
  ticketsSold?: number;

  /**
   * The revenue generated by the event.
   */
  @IsNumber()
  @IsOptional()
  revenue?: number;

  /**
   * The attendance for the event.
   */
  @IsInt()
  @IsOptional()
  attendance?: number;

  /**
   * The IDs of the outfits associated with the event.
   */
  @IsArray()
  @IsInt({ each: true })
  @IsOptional()
  outfitIds?: number[];

  /**
   * The IDs of the surprise songs associated with the event.
   */
  @IsArray()
  @IsInt({ each: true })
  surpriseSongIds?: number[];

  /**
   * The ID of the location associated with the event.
   */
  @IsInt()
  locationId: number;
}